# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import string
from secrets import choice
import bcrypt
from PyQt5 import QtCore, QtGui, QtWidgets
from cryptography.fernet import Fernet
            
def generate():

    letters = string.ascii_letters
    digits = string.digits
    special_chars = string.punctuation

    possible = ''
    res = ''

    if ui.letters.isChecked():
        possible += letters
    
    if ui.numbers.isChecked():
        possible += digits

    if ui.special.isChecked():
        possible += special_chars

    if possible != '':

        for i in range(ui.num_of_char.value()):
            res += choice(possible)

    ui.password.setText(res)

def open_data(bdata):

    file_data = bdata.strip().split("\n")

    data = []
    for i in file_data:
        data.append(i.split(" - "))

    return data

def load_data(admin):

        data = open_data(get_bdata())
        rowCount = ui.table_data.rowCount()

        if(len(data[0]) == 2):

            for i, j in data:

                if admin:
                    ui.table_data.insertRow(rowCount)
                    ui.table_data.setItem(rowCount, 0, QtWidgets.QTableWidgetItem(i))
                    ui.table_data.setItem(rowCount, 1, QtWidgets.QTableWidgetItem(j))
                else:
                    encode = str(j).encode()
                    hashed = str(bcrypt.hashpw(encode, bcrypt.gensalt()))
                    ui.table_data.insertRow(rowCount)
                    ui.table_data.setItem(rowCount, 0, QtWidgets.QTableWidgetItem(i))
                    ui.table_data.setItem(rowCount, 1, QtWidgets.QTableWidgetItem(hashed))

def add_row():
    ui.table_data.insertRow(ui.table_data.rowCount())

def delete_row():
    ui.table_data.removeRow(ui.table_data.currentRow())
    save_data()

def save_data():

    data_new = ''
    save = True
    
    for i in range(ui.table_data.rowCount()):

        if ui.table_data.item(i, 0) == None or ui.table_data.item(i, 1) == None:
            save = False

        else:

            a = ui.table_data.item(i, 0).text()
            b = ui.table_data.item(i, 1).text()

            if i == ui.table_data.rowCount() - 1:
                data_new += a + " - " + b
            else:
                data_new += a + " - " + b + "\n"

    if save:
        save_bdata(data_new)

def authenticate():

    hashed = open_sesame()

    if bcrypt.checkpw(ui.auth_input.text().encode(), hashed):
        delete_rows()
        load_data(True)
        QtCore.QTimer.singleShot(1000, enable_all)
    else:
        delete_rows()
        load_data(False)
        QtCore.QTimer.singleShot(1000, disable_all)

def delete_rows():

    for i in range(ui.table_data.rowCount()):
        ui.table_data.removeRow(0)

def enable_all():
     ui.write_to_file_but.setDisabled(False)
     ui.delete_but.setDisabled(False)
     ui.add_button_pohranjeno.setDisabled(False)

def disable_all():
    ui.write_to_file_but.setEnabled(False)
    ui.delete_but.setEnabled(False)
    ui.add_button_pohranjeno.setEnabled(False)

def connect_buttons():
    ui.generate_button.clicked.connect(generate)
    ui.delete_but.clicked.connect(delete_row)
    ui.add_button_pohranjeno.clicked.connect(add_row)
    ui.write_to_file_but.clicked.connect(save_data)
    ui.auth_but.clicked.connect(authenticate)

def load_key():
    with open('../../binary/lock.bxd', "rb") as file:
        return file.read()
    
def encrypt(key, data):
        f = Fernet(key)
        enc = f.encrypt(data)
        return enc

def decrypt(key, data):
        f = Fernet(key)
        dec = f.decrypt(data)
        return dec

def get_bdata():
     with open('../../binary/data.bxc', "rb") as file:
        return decrypt(load_key(), file.read()).decode()
     
def save_bdata(data):
     with open('../../binary/data.bxc', "wb") as file:
        file.write(encrypt(load_key(), data.encode()))

def open_sesame():
    with open('../../binary/sesame.bxd', 'rb') as file:
        return file.read()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 40, 741, 541))
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Pohranjeno = QtWidgets.QWidget()
        self.Pohranjeno.setEnabled(True)
        self.Pohranjeno.setObjectName("Pohranjeno")
        self.label = QtWidgets.QLabel(self.Pohranjeno)
        self.label.setGeometry(QtCore.QRect(280, 20, 163, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.table_data = QtWidgets.QTableWidget(self.Pohranjeno)
        self.table_data.setGeometry(QtCore.QRect(150, 110, 421, 291))
        self.table_data.setObjectName("table_data")
        self.table_data.setColumnCount(2)
        self.table_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(1, item)
        self.write_to_file_but = QtWidgets.QPushButton(self.Pohranjeno)
        self.write_to_file_but.setGeometry(QtCore.QRect(180, 440, 93, 28))
        self.write_to_file_but.setObjectName("write_to_file_but")
        self.delete_but = QtWidgets.QPushButton(self.Pohranjeno)
        self.delete_but.setGeometry(QtCore.QRect(460, 440, 93, 28))
        self.delete_but.setObjectName("delete_but")
        self.add_button_pohranjeno = QtWidgets.QPushButton(self.Pohranjeno)
        self.add_button_pohranjeno.setGeometry(QtCore.QRect(320, 440, 93, 28))
        self.add_button_pohranjeno.setObjectName("add_button_pohranjeno")
        self.tabWidget.addTab(self.Pohranjeno, "")
        self.Generiraj = QtWidgets.QWidget()
        self.Generiraj.setObjectName("Generiraj")
        self.label_2 = QtWidgets.QLabel(self.Generiraj)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 251, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.num_of_char = QtWidgets.QSpinBox(self.Generiraj)
        self.num_of_char.setGeometry(QtCore.QRect(190, 100, 41, 31))
        self.num_of_char.setMinimum(1)
        self.num_of_char.setMaximum(32)
        self.num_of_char.setProperty("value", 8)
        self.num_of_char.setObjectName("num_of_char")
        self.label_3 = QtWidgets.QLabel(self.Generiraj)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 122, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Generiraj)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 122, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Generiraj)
        self.label_5.setGeometry(QtCore.QRect(50, 220, 122, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Generiraj)
        self.label_6.setGeometry(QtCore.QRect(50, 280, 181, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.letters = QtWidgets.QCheckBox(self.Generiraj)
        self.letters.setGeometry(QtCore.QRect(140, 160, 81, 21))
        self.letters.setText("")
        self.letters.setObjectName("letters")
        self.numbers = QtWidgets.QCheckBox(self.Generiraj)
        self.numbers.setGeometry(QtCore.QRect(140, 220, 81, 21))
        self.numbers.setText("")
        self.numbers.setObjectName("numbers")
        self.special = QtWidgets.QCheckBox(self.Generiraj)
        self.special.setGeometry(QtCore.QRect(220, 280, 81, 21))
        self.special.setText("")
        self.special.setObjectName("special")
        self.password = QtWidgets.QLineEdit(self.Generiraj)
        self.password.setGeometry(QtCore.QRect(220, 390, 271, 22))
        self.password.setObjectName("password")
        self.generate_button = QtWidgets.QPushButton(self.Generiraj)
        self.generate_button.setGeometry(QtCore.QRect(440, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.generate_button.setFont(font)
        self.generate_button.setObjectName("generate_button")
        self.tabWidget.addTab(self.Generiraj, "")
        self.Auth = QtWidgets.QWidget()
        self.Auth.setObjectName("Auth")
        self.auth_input = QtWidgets.QLineEdit(self.Auth)
        self.auth_input.setGeometry(QtCore.QRect(300, 150, 113, 22))
        self.auth_input.setObjectName("auth_input")
        self.auth_but = QtWidgets.QPushButton(self.Auth)
        self.auth_but.setGeometry(QtCore.QRect(310, 250, 93, 28))
        self.auth_but.setObjectName("auth_but")
        self.tabWidget.addTab(self.Auth, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Program"))
        self.label.setText(_translate("MainWindow", "Pohranjeno"))
        item = self.table_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Platforma"))
        item = self.table_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pass"))
        self.write_to_file_but.setText(_translate("MainWindow", "Spremi"))
        self.delete_but.setText(_translate("MainWindow", "Izbriši"))
        self.add_button_pohranjeno.setText(_translate("MainWindow", "Dodaj"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Pohranjeno), _translate("MainWindow", "Pohranjeno"))
        self.label_2.setText(_translate("MainWindow", "Generiraj lozinku"))
        self.label_3.setText(_translate("MainWindow", "Broj znakova:"))
        self.label_4.setText(_translate("MainWindow", "Slova: "))
        self.label_5.setText(_translate("MainWindow", "Brojevi:"))
        self.label_6.setText(_translate("MainWindow", "Posebni znakovi:"))
        self.generate_button.setText(_translate("MainWindow", "Generiraj"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Generiraj), _translate("MainWindow", "Generiraj"))
        self.auth_but.setText(_translate("MainWindow", "Provjera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Auth), _translate("MainWindow", "Auth"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    load_data(False)
    connect_buttons()
    disable_all()
    MainWindow.show()
    sys.exit(app.exec_())
